### ISSUE TITLE
Image on quay.io is not up-to-date

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/javapackages-validator#165]
Container image at https://quay.io/repository/fedora-java/javapackages-validator is not up-to-date.
The last build in the registry is from October 22, commit dd21daf 
Since then several commits were added, but no image was built.

**Comment by mkoncek** [comment]
Fixed by resetting the trigger and merging the dependabot PR.
I wonder if there is a way to get notified when quay.io disables the triggers.
