### ISSUE TITLE
Add a check for checking that filepath entries in maven-metadata xml files point to existing files

### ISSUE THREAD

**Issue by mkoncek** [fedora-java/javapackages-validator#31]

**Comment by mizdebsk** [comment]
In addition to that it would be good to validate maven-metadata against [XML Schema (XSD)](https://en.wikipedia.org/wiki/XML_Schema_(W3C)) ([metadata-2.0.0.xsd](https://fedora-java.github.io/xmvn/xsd/metadata-2.0.0.xsd))

**Comment by mizdebsk** [comment]
This is implemented in https://github.com/fedora-java/javapackages-validator/pull/29/commits/ba8c1fc5723dbebd17729f87a53c00aebb9053ed
