### ISSUE TITLE
Add a check for NVR metadata in JAR files

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/javapackages-validator#33]
Ensure that every JAR file has manifest entry with appropriate Rpm-Name, Rpm-Epoch, Rpm-Version and Rpm-Release attributes.

**Comment by mkoncek** [comment]
Implemented by 9a9d785601b6d4f9e0364adeb4799b684bde6904 and 09b980f200c98508d9970e063976466a9c474211
