### ISSUE TITLE
Continuous delivery

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/javapackages-validator#4]
Once validator is automatically built and tested (this is feature #3), its binary artifacts should be deployed to a repository, like quay.io (for container images) or Copr (for RPM packages).

**Comment by mkoncek** [comment]
I would like to try out Packit integration.
You need to enable it on this repository https://github.com/marketplace/packit-as-a-service.
Then we need to set up a Copr namespace where I would have access to (probably @java).
Then we need to request the packit team to map this github namespace / acccount to the Copr one, I am not sure about the details of it.

**Comment by mizdebsk** [comment]
Packit-as-a-Service GitHub app has been installed.

**Comment by mizdebsk** [comment]
I believe continuous delivery is already implemented by building each commit in master branch as a container image on quay.io
@mkoncek Is there anything else left to do for this?

**Comment by mkoncek** [comment]
Yes, I would say so.
Although we still haven't explored what benefits Packit would offer us.
I don't know whether it would be worth the time trying to add the project when this already works.

**Comment by mkoncek** [comment]
This issue is already resolved, see: https://quay.io/repository/fedora-java/javapackages-validator?tab=tags
