### ISSUE TITLE
New lines in HTML output are not rendered correctly

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/javapackages-validator#82]
In HTML output new lines should be replaced with relevant HTML code `<br>`, otherwise they are rendered as whitespace.

**Comment by mizdebsk** [comment]
Workaround: always use decorated new line, eg. `Decorated.plain("\n")`

**Comment by mkoncek** [comment]
I wonder what happened to: https://github.com/fedora-java/javapackages-validator/blob/master/src/main/java/org/fedoraproject/javapackages/validator/HtmlDecorator.java#L26
