### ISSUE TITLE
Add support for files without content

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/javapackages-validator#86]
Currently validator does not recognize package files with no content, such as directories or %ghost files.
That should be fixed.

**Comment by mkoncek** [comment]
You mean RPM files?

**Comment by mkoncek** [comment]
Can you explain further what you mean? There is `util.Common.rpmFilesAndSymlinks` static function that goes over the actual members of the `.cpio` archive, in that sense it behaves as expected.

**Comment by mizdebsk** [comment]
The point is that not all rpm files are members of the cpio archive.
For example, `/usr/bin/mvn` file is part of `maven` package, but JPV does not see that file.

**Comment by mkoncek** [comment]
I believe the fix requires update of upstream `java-deptools-native`.

**Comment by mizdebsk** [comment]
> I believe the fix requires update of upstream `java-deptools-native`.

There is such support in version 1.2.0.
