### ISSUE TITLE
Check that all JARs and POMs have corresponding metadata

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/javapackages-validator#88]
MavenMetadataValidator should check if all packaged JAR files have corresponding Maven metadata.
If not, "warn" or at least print "info".
In case there is a POM without metadata, "fail" the check.

**Comment by mkoncek** [comment]
Good, please also update the class-level comment which describes what the validator does.

**Comment by mizdebsk** [comment]
> Good, please also update the class-level comment which describes what the validator does.

The comment was already outdated, but sure, I will update it.

**Comment by mkoncek** [comment]
Thank you.
